# Generated by Django 2.1.7 on 2019-04-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_aula', models.DateTimeField(blank=True, null=True, verbose_name='Data Aula')),
                ('situacao', models.IntegerField(choices=[(1, 'Disponivel'), (2, 'Agendado'), (3, 'Bloqueado'), (4, 'Atendido')], default=1, verbose_name='Situação')),
                ('nome_paciente', models.CharField(max_length=80, verbose_name='Nome')),
                ('telefone_paciente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('disponivel', models.BooleanField(default=True)),
                ('assunto', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_aluno', models.CharField(blank=True, max_length=80, null=True)),
                ('curso', models.BooleanField(default=False)),
                ('conteudo', models.CharField(blank=True, max_length=700, null=True)),
                ('disponivel_curso', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_aula',
                'ordering': ['dt_aula'],
                'default_related_name': 'aulas',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('aprovacao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.DateField(blank=True, null=True)),
                ('ate', models.DateField(blank=True, null=True)),
                ('dia_semana', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], max_length=13, verbose_name='Dia')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('intervalo', models.IntegerField(default=0, verbose_name='Intervalo')),
            ],
            options={
                'ordering': ['dia_semana'],
                'default_related_name': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(blank=True, max_length=10)),
                ('conteudo', models.CharField(blank=True, max_length=300)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sobrenome', models.CharField(max_length=80)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='media/')),
                ('fotocatalogo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('descricao', models.CharField(blank=True, max_length=56)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Disciplina')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='index.Professor'),
        ),
        migrations.AddField(
            model_name='aula',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='index.Grade'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='index.Professor'),
        ),
    ]
