# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-15 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sobrenome',
            field=models.CharField(max_length=80),
        ),
    ]
