# Generated by Django 2.1.7 on 2019-03-25 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0020_auto_20190325_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='professoresinteressados',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='professoresinteressados',
            name='user',
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sobrenome',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Aulas',
        ),
        migrations.DeleteModel(
            name='ProfessoresInteressados',
        ),
    ]
