# Generated by Django 2.1.7 on 2019-03-28 01:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20190325_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='dia_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], max_length=13, verbose_name='Dia'),
        ),
    ]
