# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20190322_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='index.Professor'),
        ),
    ]
