# Generated by Django 2.1.7 on 2019-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20190328_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='descricao',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
