# Generated by Django 2.1.7 on 2019-04-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_professor_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(blank=True, max_length=10)),
                ('conteudo', models.CharField(blank=True, max_length=300)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Aula')),
            ],
        ),
    ]
