# Generated by Django 2.1.7 on 2019-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
