# Generated by Django 2.1.7 on 2019-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_aula_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='fotocatalogo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
