# Generated by Django 2.1.7 on 2019-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20190404_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='nome_aluno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
