# Generated by Django 2.1.7 on 2019-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_aula_nome_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_aluno', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_aluno', models.CharField(blank=True, max_length=100, null=True)),
                ('aula_assunto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
