# Generated by Django 2.1.7 on 2019-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_delete_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.BooleanField(default=False),
        ),
    ]
