# Generated by Django 2.1.7 on 2019-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_aula_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='disponivel_curso',
            field=models.BooleanField(default=True),
        ),
    ]
