# Generated by Django 2.1.7 on 2019-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_aula_disponivel_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='descricaocurta',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='professor',
            name='descricao',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
