# Generated by Django 2.1.7 on 2019-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_auto_20190406_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='intervalo',
            field=models.IntegerField(blank=True, verbose_name='Intervalo'),
        ),
    ]
