# Generated by Django 2.1.7 on 2019-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_auto_20190406_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='intervalo',
            field=models.IntegerField(default=0, verbose_name='Intervalo'),
        ),
    ]
