# Generated by Django 2.1.7 on 2019-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_auto_20190406_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='conteudo',
            field=models.CharField(max_length=300),
        ),
    ]
