# Generated by Django 2.1.7 on 2019-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20190408_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='conteudo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
