# Generated by Django 2.1.7 on 2019-04-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20190408_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='media/')),
                ('conteudo', models.CharField(blank=True, max_length=80, null=True)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('informacoes', models.CharField(blank=True, max_length=80, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Aluno')),
            ],
        ),
    ]
