# Generated by Django 2.1.7 on 2019-04-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.Aula'),
        ),
    ]
