# Generated by Django 2.1.7 on 2019-04-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0048_auto_20190418_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
    ]
