# Generated by Django 2.1.7 on 2019-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0049_remove_curso_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(to='index.Aluno'),
        ),
    ]
