# Generated by Django 2.1.7 on 2019-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_curso_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='index.Aluno'),
        ),
    ]
