# Generated by Django 2.1.7 on 2019-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0051_auto_20190418_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='index.Curso'),
        ),
    ]
