# Generated by Django 2.1.7 on 2019-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0052_auto_20190418_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursos',
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='index.Aluno'),
        ),
    ]
